### ISSUE TITLE
Failure to Build

### ISSUE THREAD

**Issue by Thomas-Smyth** [creativetimofficial/argon-dashboard-react#3]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

React build to produce a successful build for deployment.

# Current Behavior

React build error:
```
yarn run build
yarn run v1.12.3
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Lexical error on line 1: Unrecognized text.
  Erroneous area:
1: 100% - $icon-size-xl - 1
^.........^


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

# Failure Information (for bugs)

See above.

## Steps to Reproduce

Simply running the `yarn run build` command throws this error.

## Context

I have made very few changes from the original download and none of these revolves around the SCSS / CSS. **Edit** - Just tested with the original copy I downloaded from your website and it throws the same error when building.

* Device: Desktop PC
* Operating System: Windows 10
* Browser and Version: N/A

## Failure Logs

See above.

**Comment by Thomas-Smyth** [comment]
This looks to be the problematic section of `argon-dashboard-react.css` that is causing the issues.
```css
.icon-xl {
  width: 5rem;
  height: 5rem; }
  .icon-xl i, .icon-xl svg {
    font-size: 4.25rem; }
  .icon-xl + .icon-text {
    width: calc(100% - $icon-size-xl - 1); }

.icon-lg {
  width: 4rem;
  height: 4rem; }
  .icon-lg i, .icon-lg svg {
    font-size: 3.25rem; }
  .icon-lg + .icon-text {
    width: calc(100% - $icon-size-lg - 1); }

.icon-sm {
  width: 2rem;
  height: 2rem; }
  .icon-sm i, .icon-sm svg {
    font-size: 1.25rem; }
  .icon-sm + .icon-text {
    width: calc(100% - $icon-size-sm - 1); }
```

Manually copying those variables to the CSS file allows for a successful build.
